server:
  port: 8088
spring:
  application:
    name: apiGateWay

---
spring:
  profiles: dev
zuul:
#  sensitive-headers:
  routes:
#    product:
#      serviceId: product
#      path: /myproduct/**
      #简洁写法
    product: /myproduct/**
    #忽略的路由
  ignored-patterns:
    - /product/product/server/msg
