server:
  port: 8090
  servlet:
    context-path: /order

spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_order?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
      show-sql: true
      database: mysql

product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule
