server:
  servlet:
    context-path: /product
#  port: 8091

spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_product?chracterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    addresses: 192.168.90.100
    port: 5672
    username: guest
    password: guest
