server:
  port: 8083
  servlet:
    context-path: /user
---
spring:
  profile: dev
  rabbitmq:
    host: 192.168.90.100
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.90.100
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
